// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFCbV2ivPipsi55RSOtFQjVpiTgOmAQY',
    appId: '1:36984319417:web:df691d529e971e77011a68',
    messagingSenderId: '36984319417',
    projectId: 'lingobill-be2fd',
    authDomain: 'lingobill-be2fd.firebaseapp.com',
    storageBucket: 'lingobill-be2fd.firebasestorage.app',
    measurementId: 'G-C6GXBSXQDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Kha0VaaxFaCwwEo6LH8CxQMFdiGbVqU',
    appId: '1:36984319417:android:7baf520c97a532f1011a68',
    messagingSenderId: '36984319417',
    projectId: 'lingobill-be2fd',
    storageBucket: 'lingobill-be2fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG87q-cF1TH-t8qdzXvZZZLPMN_weuwtg',
    appId: '1:36984319417:ios:788eff011505c456011a68',
    messagingSenderId: '36984319417',
    projectId: 'lingobill-be2fd',
    storageBucket: 'lingobill-be2fd.firebasestorage.app',
    iosBundleId: 'com.example.bilingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG87q-cF1TH-t8qdzXvZZZLPMN_weuwtg',
    appId: '1:36984319417:ios:788eff011505c456011a68',
    messagingSenderId: '36984319417',
    projectId: 'lingobill-be2fd',
    storageBucket: 'lingobill-be2fd.firebasestorage.app',
    iosBundleId: 'com.example.bilingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFCbV2ivPipsi55RSOtFQjVpiTgOmAQY',
    appId: '1:36984319417:web:a558cc28312ed46f011a68',
    messagingSenderId: '36984319417',
    projectId: 'lingobill-be2fd',
    authDomain: 'lingobill-be2fd.firebaseapp.com',
    storageBucket: 'lingobill-be2fd.firebasestorage.app',
    measurementId: 'G-745PNWEZ49',
  );
}
